-- Days 1-6 ka schema, jaisa Hibernate ne ddl-auto: update se banaya tha.
--
-- Yeh baseline hai: is file ke baad schema ka maalik Flyway hai aur Hibernate sirf
-- validate karta hai. Aage har badlaav ek nayi V2, V3 file hai — is file ko chhuna nahi,
-- kyunki Flyway applied migrations ka checksum rakhta hai aur edit hui file pe boot rok deta hai.
--
-- Constraint names dump se badle gaye hain (Hibernate 'ukr43af9ap4edm43mmtq01oddj6' jaise
-- naam deta hai). Yeh surakshit hai: Hibernate ka validate tables, columns aur types dekhta hai,
-- constraint ya index ke naam nahi.

create table users (
    id         bigint       generated by default as identity primary key,
    username   varchar(255) not null,
    password   varchar(255) not null,
    name       varchar(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,

    constraint uk_users_username unique (username)
);

create table projects (
    id          bigint       generated by default as identity primary key,
    owner_id    bigint       not null,
    name        varchar(255) not null,
    description text,
    status      varchar(20)  not null,
    preview_url varchar(255),

    -- Optimistic locking. Default 0 zaroori hai: iske bina populated table pe
    -- yeh column add karna Postgres reject kar deta hai
    version     bigint       not null default 0,

    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,

    -- Enum ka check constraint. Iski keemat yeh hai ki nayi enum value ke liye ek
    -- migration bhi likhni padegi, sirf Java enum badalna kaafi nahi hoga
    constraint projects_status_check
        check (status in ('DRAFT', 'GENERATING', 'READY', 'FAILED'))
);

-- owner_id pe koi foreign key nahi, jaan-boojh ke: cross-module reference id se hai
-- taaki service split ke baad alag databases mein bhi tike. Index isliye hai kyunki
-- har project read owner se filter hota hai
create index idx_project_owner on projects (owner_id);

create table generated_files (
    id         bigint       generated by default as identity primary key,
    project_id bigint       not null,
    path       varchar(255) not null,
    content    text         not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,

    -- Ek project mein ek path ek hi baar. Regenerate delete-then-insert karta hai,
    -- aur yahi constraint us order ko galat hone pe pakadta hai
    constraint uk_generated_file_project_path unique (project_id, path)
);

create index idx_generated_file_project on generated_files (project_id);

create table chat_messages (
    id         bigint      generated by default as identity primary key,
    project_id bigint      not null,
    role       varchar(20) not null,
    content    text        not null,

    -- updated_at yahan nahi hai: history append-only hai
    created_at timestamp(6) with time zone not null,

    constraint chat_messages_role_check
        check (role in ('USER', 'ASSISTANT'))
);

create index idx_chat_message_project on chat_messages (project_id);
